/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as NewTaskRouteImport } from './routes/new-task'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaskTaskIdRouteImport } from './routes/task.$taskId'

const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const NewTaskRoute = NewTaskRouteImport.update({
  id: '/new-task',
  path: '/new-task',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskTaskIdRoute = TaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new-task': typeof NewTaskRoute
  '/queue': typeof QueueRoute
  '/task/$taskId': typeof TaskTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new-task': typeof NewTaskRoute
  '/queue': typeof QueueRoute
  '/task/$taskId': typeof TaskTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new-task': typeof NewTaskRoute
  '/queue': typeof QueueRoute
  '/task/$taskId': typeof TaskTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new-task' | '/queue' | '/task/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new-task' | '/queue' | '/task/$taskId'
  id: '__root__' | '/' | '/new-task' | '/queue' | '/task/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewTaskRoute: typeof NewTaskRoute
  QueueRoute: typeof QueueRoute
  TaskTaskIdRoute: typeof TaskTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-task': {
      id: '/new-task'
      path: '/new-task'
      fullPath: '/new-task'
      preLoaderRoute: typeof NewTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/$taskId': {
      id: '/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/task/$taskId'
      preLoaderRoute: typeof TaskTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewTaskRoute: NewTaskRoute,
  QueueRoute: QueueRoute,
  TaskTaskIdRoute: TaskTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
